#!/bin/bash

# This script generates a VLESS link.
# It can be called with the following arguments:
# -u <uuid>
# -n <name>

while getopts u:n: flag
do
    case "${flag}" in
        u) uuid=${OPTARG};;
        n) name=${OPTARG};;
    esac
done

if [ -z "$uuid" ] || [ -z "$name" ]; then
    echo "Usage: $0 -u <uuid> -n <name>"
    exit 1
fi

CONFIG=/etc/sing-box/config.json

SHORT_ID=$(jq -r '.inbounds[0].tls.reality.short_id[0]' $CONFIG)
SERVER=$(jq -r '.inbounds[0].tls.server_name' $CONFIG)

echo "vless://$uuid@$SERVER:443/?type=tcp&encryption=none&flow=xtls-rprx-vision&packetEncoding=xudp&sni=$SERVER&fp=chrome&security=reality&pbk=$PUBLIC_KEY&sid=$SHORT_ID#$name"
