services:
  sing-box:
    container_name: sing-box
    build:
      context: sing-box
      args:
        RELEASE: v1.11.14
    ports:
      - "443:443"
    environment:
      SERVER: DOMAIN
      PUBLIC_KEY: PBK
      UUID: UUID
      PRIVATE_KEY: PRK
      SHORT_ID: SHORTID
    # volumes:
    #  - ./config:/etc/sing-box/

  caddy:
    build:
      context: ./caddy
    container_name: caddy
    environment:
      SERVER: DOMAIN
      DEBUG: 0
    restart: always
    volumes:
      # - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      # - ./caddy/srv:/srv
    ports:
      - "80:80"
