services:
  sing-box:
    container_name: sing-box
    image: ftroitsky/sing-box:v1.12.5
    ports:
      - "443:443"
      - "51820:51820/udp"
    environment:
      SERVER: ${SERVER}
      PUBLIC_KEY: ${PUBLIC_KEY}
      UUID: ${UUID}
      PRIVATE_KEY: ${PRIVATE_KEY}
      SHORT_ID: ${SHORT_ID}
    restart: always
    # Enable for custom config (multiple accounts for example)
    # volumes:
    #  - ./config:/etc/sing-box/

  caddy:
    container_name: caddy
    image: ftroitsky/caddy-self-masking:2.10.0
    ports:
      - "80:80"
    environment:
      SERVER: ${SERVER}
      DEBUG: 0
    restart: always
    volumes:
      - ./caddy_data:/data
