services:
  sing-box:
    container_name: sing-box
    build:
      context: sing-box
      args:
        RELEASE: v1.12.5
    ports:
      - "443:443"
      - "51820:51820/udp"
    environment:
      SERVER: ${SERVER}
      PUBLIC_KEY: ${PUBLIC_KEY}
      UUID: ${UUID}
      PRIVATE_KEY: ${PRIVATE_KEY}
      SHORT_ID: ${SHORT_ID}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
    volumes:
      - ./sing-box:/opt
      - ./devices:/etc/sing-box/devices

  caddy:
    build:
      context: ./caddy
    container_name: caddy
    environment:
      SERVER: ${SERVER}
      DEBUG: 0
    restart: always
    volumes:
      # - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      # - ./caddy/srv:/srv
    ports:
      - "80:80"
