name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - README.EN.md
      - .github/workflows/dockerhub-description.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4.0.2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: itdoginfo/sing-box
        readme-filepath: ./README.EN.md